DROP TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE
(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(20),
    DEPTNO NUMBER(2),
    SAL NUMBER(8)
);

INSERT INTO EMPLOYEE VALUES (101,'Amit',10,25000);
INSERT INTO EMPLOYEE VALUES (102,'Riya',20,30000);
INSERT INTO EMPLOYEE VALUES (103,'Neha',10,28000);
INSERT INTO EMPLOYEE VALUES (104,'Rahul',30,35000);
INSERT INTO EMPLOYEE VALUES (105,'Priya',20,27000);

COMMIT;

SET SERVEROUTPUT ON;

DECLARE
BEGIN
    UPDATE EMPLOYEE
    SET SAL = SAL + 5000
    WHERE DEPTNO = 10;

    IF SQL%ROWCOUNT > 0 THEN
        DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT || ' Record(s) Updated.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('No Record Found.');
    END IF;

    COMMIT;
END;
/