DROP TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE
(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(20),
    DEPTNO NUMBER(2),
    SAL NUMBER(8)
);

INSERT INTO EMPLOYEE VALUES (101,'Amit',10,25000);
INSERT INTO EMPLOYEE VALUES (102,'Riya',20,50000);
INSERT INTO EMPLOYEE VALUES (103,'Neha',30,40000);
INSERT INTO EMPLOYEE VALUES (104,'Rahul',10,35000);
INSERT INTO EMPLOYEE VALUES (105,'Priya',20,45000);
INSERT INTO EMPLOYEE VALUES (106,'Karan',30,55000);
INSERT INTO EMPLOYEE VALUES (107,'Pooja',10,30000);

COMMIT;

SET SERVEROUTPUT ON;

DECLARE
    i NUMBER := 0;

    CURSOR c1 IS
        SELECT ENAME, SAL
        FROM EMPLOYEE
        ORDER BY SAL DESC;

BEGIN
    FOR emp IN c1
    LOOP
        i := i + 1;

        EXIT WHEN i > 3;

        DBMS_OUTPUT.PUT_LINE('Name : ' || emp.ENAME);
        DBMS_OUTPUT.PUT_LINE('Salary : ' || emp.SAL);
        DBMS_OUTPUT.PUT_LINE('--------------------');
    END LOOP;
END;
/