DROP TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE
(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(20),
    DEPTNO NUMBER(2),
    SAL NUMBER(8)
);

INSERT INTO EMPLOYEE VALUES (101,'Amit',10,25000);
INSERT INTO EMPLOYEE VALUES (102,'Ankit',20,30000);
INSERT INTO EMPLOYEE VALUES (103,'Neha',10,28000);
INSERT INTO EMPLOYEE VALUES (104,'Anita',30,35000);
INSERT INTO EMPLOYEE VALUES (105,'Priya',20,27000);

COMMIT;

SET SERVEROUTPUT ON;

DECLARE
    CURSOR c1 IS
        SELECT *
        FROM EMPLOYEE
        WHERE ENAME LIKE 'A%';

BEGIN
    FOR emp IN c1
    LOOP
        DBMS_OUTPUT.PUT_LINE('Employee No : ' || emp.EMPNO);
        DBMS_OUTPUT.PUT_LINE('Name : ' || emp.ENAME);
        DBMS_OUTPUT.PUT_LINE('Department : ' || emp.DEPTNO);
        DBMS_OUTPUT.PUT_LINE('Salary : ' || emp.SAL);
        DBMS_OUTPUT.PUT_LINE('--------------------');
    END LOOP;
END;
/