DROP TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE
(
    EMP_ID NUMBER(5),
    EMP_NAME VARCHAR2(30),
    AGE NUMBER(3),
    BASIC_SAL NUMBER(10,2)
);

INSERT INTO EMPLOYEE VALUES (101, 'ANISHA', 20, 30000);
INSERT INTO EMPLOYEE VALUES (102, 'RIYA', 50, 45000);
INSERT INTO EMPLOYEE VALUES (103, 'PRIYA', 25, 35000);

COMMIT;

SET SERVEROUTPUT ON;

DECLARE
    V_SALARY EMPLOYEE.BASIC_SAL%TYPE;
BEGIN
    SELECT BASIC_SAL
    INTO V_SALARY
    FROM EMPLOYEE
    WHERE AGE = 50;

    DBMS_OUTPUT.PUT_LINE('Basic Salary: ' || V_SALARY);

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('No employee found whose age is 50.');

    WHEN TOO_MANY_ROWS THEN
        DBMS_OUTPUT.PUT_LINE('More than one employee is 50 years old.');
END;
/