DROP TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE
(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(20),
    SAL NUMBER(8)
);

INSERT INTO EMPLOYEE VALUES (101, 'Amit', 25000);
INSERT INTO EMPLOYEE VALUES (102, 'Riya', 30000);
INSERT INTO EMPLOYEE VALUES (103, 'Neha', 28000);

COMMIT;

SET SERVEROUTPUT ON;

DECLARE
    v_sal NUMBER;
BEGIN
    SELECT SAL INTO v_sal
    FROM EMPLOYEE
    WHERE ENAME = 'Riya';

    v_sal := TO_NUMBER('ABC');

    DBMS_OUTPUT.PUT_LINE('Salary = ' || v_sal);

EXCEPTION
    WHEN INVALID_NUMBER THEN
        DBMS_OUTPUT.PUT_LINE('Invalid number.');
END;
/